"""
GeAR Agent Prompt模板

包含各个Agent组件使用的Prompt模板。
"""

from .query_analysis import QUERY_ANALYSIS_PROMPT, QUERY_ANALYSIS_SYSTEM
from .node_selection import INITIAL_NODE_SELECTION_PROMPT, NEXT_HOP_SELECTION_PROMPT
from .path_reasoning import PATH_EVALUATION_PROMPT

__all__ = [
    'QUERY_ANALYSIS_PROMPT',
    'QUERY_ANALYSIS_SYSTEM',
    'INITIAL_NODE_SELECTION_PROMPT',
    'NEXT_HOP_SELECTION_PROMPT',
    'PATH_EVALUATION_PROMPT'
]


